name: customer_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  http: ^1.2.0
  shared_preferences: ^2.2.2
  local_auth: ^2.2.0
  flutter_map: ^8.3.1
  latlong2: ^0.10.1
  image_picker: ^1.2.3
  geolocator: ^14.0.3
  animated_notch_bottom_bar: ^1.0.4
  qr_flutter: ^4.1.0
  flutter_local_notifications: ^22.3.0
  workmanager: ^0.10.9
  permission_handler: ^11.3.1
  firebase_core: ^4.14.0
  firebase_messaging: ^16.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
